In [ ]:
import numpy as np

In [ ]:
list=[1,2,3,4]

In [ ]:
type(list)

list

In [ ]:
arr=np.array(list)
arr


array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.size

4

In [ ]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z1=np.ones(5)
z1

array([1., 1., 1., 1., 1.])

In [ ]:
#creating a 1 D array
z2=np.array([1,2,3,4])

In [ ]:
z2.ndim

1

In [ ]:
z2.shape

(4,)

In [ ]:
# 2D arrays
z3=np.array([[1,2,3],[4,5,6],[7,8,9],[9,10,11]])
z3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11]])

In [ ]:
z3.ndim

2

In [ ]:
z3.shape

(4, 3)

In [ ]:
# 3D array
z3=z3.reshape(3,2,2)
z3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9,  9],
        [10, 11]]])

In [ ]:
z3.ndim

3

In [ ]:
z3.shape

(3, 2, 2)

In [ ]:
z3=z3.reshape(3,4)
z3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  9, 10, 11]])

# **Accessing 1D array**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
arr[4]

5

In [ ]:
arr[1]+arr[2]

5

# **Accessing 2D array**

In [ ]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
print("2nd element in 1st dim",arr1[0,1])

2nd element in 1st dim 2


In [ ]:
#Lineraly spaced elements- linspace(start,end,number of elements req)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#identity matrix
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x.shape

(3, 3)

In [ ]:
#Create random number of int type between 0, 10 ...
#also specify how many elements you want
np.random.randint(0,10,15)


array([5, 7, 6, 7, 8, 5, 2, 4, 5, 2, 4, 0, 6, 3, 2])

In [ ]:
np.random.rand(3,3)

array([[0.9091158 , 0.88800624, 0.41914673],
       [0.82761715, 0.25864358, 0.98359383],
       [0.14165255, 0.29621025, 0.34849727]])

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr1.max()

10

In [ ]:
arr1.argmax()

9

In [ ]:
arr1.min()

1

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## **Slicing**

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:4] #arr[start value,end value+1]

array([2, 3, 4])

In [ ]:
z3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  9, 10, 11]])

In [ ]:
z3[0:1,0:2]

array([[1, 2]])

In [ ]:
z3[2:3,1:4]

array([[ 9, 10, 11]])

In [ ]:
z3[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
p=np.arange(0,10,2)

In [ ]:
q=np.arange(11,21,2)

In [ ]:
c=p+q


In [ ]:
c

array([11, 15, 19, 23, 27])

In [ ]:
p

array([0, 2, 4, 6, 8])

In [ ]:
q

array([11, 13, 15, 17, 19])

In [ ]:
np.sqrt(c)

array([3.31662479, 3.87298335, 4.35889894, 4.79583152, 5.19615242])

In [ ]:
np.sin(c)

array([-0.99999021,  0.65028784,  0.14987721, -0.8462204 ,  0.95637593])

In [ ]:
d=c.copy() #does not reflect the changes if there are any

In [ ]:
d

array([11, 15, 19, 23, 27])

In [ ]:
d=c.view()

In [ ]:
c[0]=45

In [ ]:
c

array([45, 15, 19, 23, 27])

In [ ]:
d

array([45, 15, 19, 23, 27])